export const STORAGE_KEYS = {
    GET_USER: 'getUserDetails',
    GET_PERSONAL_DETAIL: 'getAllPersonalDetails',
    GET_CITIES: 'getAllCities',
    GET_LANGUAGE: 'getAllLanguages',
    GET_LANGUAGE_AUTH: 'getAllLanguagesAuth',
    GET_PRICACY_POLICY: 'getPrivicyPolicy',
    GET_ADDRESS: 'getAllAddresses',
    GET_NOTIFICATION: 'getAllNotification',
    COUNT_NOTIFICATION: 'getNotificationSeen',
    GET_AVALIABLE_PROMOCODE: 'getAvaliablePromoCode',
    GET_USED_PROMOCODE: 'getUsedPromoCode',
    GET_EARNINGS: 'getTotalEarning',
    GET_TRIP_REPORT: 'getTripReportID',
    GET_RECEIPT: 'getReceipt',
    GET_TRIP_POLYLINE: 'getTripPolyline',
    GET_FINSIH_RIDE_POLYLINE: 'getFinishRidePolyline',
    GET_TRIP_DETAIL: 'getTripDetail',
    GET_ALL_RIDE_SCHEDULED: 'getAllRideScheduled',
    GET_RIDE_HISTORY: 'getRideHistory',
    GET_ON_GOING_RIDE: 'getOngoingRide',
    GET_EARNING_DETAIL: 'getEarningDetail',
    GET_ALL_RIDE_DETAILS: 'getAllRideDetails',
    GET_CHATLIST: 'chatList',
    TOKEN: 'TOKEN',
    IS_VERIFIED: 'IS_VERIFIED',
    RIDE_DATE: 'RIDE_DATE',
    BANKING_INFO: 'BANKING_INFO',
    GET_DASHBOARD_LINK: 'getDashboardlink',
    IS_KILLED: 'IS_KILLED',
    GET_ALL_EVENTS: "GET_ALL_EVENTS"
  };
  